services:
  mosquee-zn-gestion:
    image: nginx:alpine
    container_name: mosquee-zn-gestion
    volumes:
      - ~/workspace/mosquee-zn-gestion:/usr/share/nginx/html:ro
      - ~/workspace/mosquee-zn-gestion/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "30903:80"
    restart: unless-stopped
